const portfolioObj = [
  {
    id: "1",
    workCardClass: "work-section work-1",
    mobileImg: "",
    desktopImg: "img/1.Snapshoot Portfolio.png",
    separatorImg: "img/separator-icon.png",
    projectName: "Tonic",
    companyName: "Canopy",
    position: "Back End Dev",
    projectYear: 2015,
    projectDetails:
      "A daily selection of privately personalized reads; no accounts or sign-ups required.",
    projectTools: ["html", "Ruby on rails", "css", "javaScript"],
    projectBtnText: "See Project",
    modalBtnText: "See Live",
    codeBtnText: "See Source",
  },
  {
    id: "2",
    workCardClass: "work-section reverse work-2",
    mobileImg: "",
    desktopImg: "img/2.Snapshoot Portfolio.png",
    separatorImg: "img/separator-icon.png",
    projectName: "Multi-Post Stories",
    companyName: "FACEBOOK",
    position: "Full Stack Dev",
    projectYear: 2015,
    projectDetails:
      "Experimental content creation feature that allows users" +
      "to add to an existing story over the course of a day without spamming their friends.",
    projectTools: ["html", "Ruby on rails", "css", "javaScript"],
    projectBtnText: "See Project",
    modalBtnText: "See Live",
    codeBtnText: "See Source",
  },
  {
    id: "3",
    workCardClass: "work-section work-3",
    mobileImg: "",
    desktopImg: "img/Snapshoot Portfolio5.png",
    separatorImg: "img/separator-icon.png",
    projectName: "Facebook 360",
    companyName: "FACEBOOK",
    position: "Full Stack Dev",
    projectYear: 2015,
    projectDetails:
      "Exploring the future of media in Facebook's first Virtual Reality app; a place to discover and enjoy 360 photos and videos on Gear VR",
    projectTools: ["html", "Ruby on rails", "css", "javaScript"],
    projectBtnText: "See Project",
    modalBtnText: "See Live",
    codeBtnText: "See Source",
  },
  {
    id: "4",
    workCardClass: "work-section work-4 reverse",
    mobileImg: "",
    desktopImg: "img/ubersnapshot.png",
    separatorImg: "img/separator-icon.png",
    projectName: "Uber Navigation",
    companyName: "Uber",
    position: "Lead Developer",
    projectYear: 2018,
    projectDetails:
      "A smart assistant to make driving more safe, efficient, and fun by unlocking your most expensive computer: your car.",
    projectTools: ["html", "Ruby on rails", "css", "javaScript"],
    projectBtnText: "See Project",
    modalBtnText: "See Live",
    codeBtnText: "See Source",
  },
];

export default portfolioObj;
